#!/usr/bin/env bash
#
# Valheim Dedicated Server installer for Debian 13
# Interactive setup: run as root: sudo ./install.sh
#
set -euo pipefail

# ------------------------------------------------------------------
# Paths and constants (edit here if you need something custom)
# ------------------------------------------------------------------
STEAM_USER="valheim"
STEAMCMD_DIR="/opt/steamcmd"
VALHEIM_DIR="/opt/valheim"
CONFIG_DIR="/etc/valheim"
ENV_FILE="${CONFIG_DIR}/valheim.env"
SCRIPTS_SRC="$(cd "$(dirname "$0")" && pwd)/scripts"

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
prompt() {
    local __result=$1
    local __question=$2
    local __default=$3
    local __value=""
    while [ -z "$__value" ]; do
        read -r -p "$__question [${__default}]: " __value
        __value="${__value:-$__default}"
    done
    eval "$__result=\$__value"
}

if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root (sudo ./install.sh)"
    exit 1
fi

# ------------------------------------------------------------------
# Gather settings
# ------------------------------------------------------------------
echo "==============================================="
echo " Valheim Dedicated Server - Interactive Setup "
echo "==============================================="
echo ""

prompt SERVER_NAME "Server name (shown in the server list)" "My Valheim Server"
prompt WORLD_NAME "World name" "Midgard"
prompt SERVER_PORT "Game port (2 more UDP ports follow it)" "2456"

while true; do
    prompt SERVER_PASSWORD "Server password (min 5 characters)" "change-me"
    if [ "${#SERVER_PASSWORD}" -ge 5 ]; then
        break
    fi
    echo "ERROR: Password must be at least 5 characters long."
done

prompt PUBLIC_LISTING "Public server? (1 = listed in community list, 0 = private)" "1"
prompt BACKUP_RETENTION "Backup retention in days" "7"

echo ""
echo "Summary:"
echo "  Server name : $SERVER_NAME"
echo "  World       : $WORLD_NAME"
echo "  Password    : $SERVER_PASSWORD"
echo "  Port (UDP)  : $SERVER_PORT-$((SERVER_PORT + 2))"
echo "  Public      : $PUBLIC_LISTING"
echo ""
read -r -p "Proceed with installation? [y/N]: " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
fi

# ------------------------------------------------------------------
# Install dependencies
# ------------------------------------------------------------------
echo ">>> Installing required packages..."
apt-get update
apt-get install -y curl lib32gcc-s1 ca-certificates tar cron

# ------------------------------------------------------------------
# Create dedicated service user
# ------------------------------------------------------------------
if id -u "$STEAM_USER" &>/dev/null; then
    echo ">>> Service user '$STEAM_USER' already exists, skipping."
else
    echo ">>> Creating service user '$STEAM_USER'..."
    useradd -m -r -s /usr/sbin/nologin "$STEAM_USER"
fi

# ------------------------------------------------------------------
# Install SteamCMD
# ------------------------------------------------------------------
if [ ! -f "${STEAMCMD_DIR}/steamcmd.sh" ]; then
    echo ">>> Installing SteamCMD..."
    mkdir -p "$STEAMCMD_DIR"
    curl -sSL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz \
        | tar -xz -C "$STEAMCMD_DIR"
    chown -R "$STEAM_USER":"$STEAM_USER" "$STEAMCMD_DIR"
else
    echo ">>> SteamCMD already installed, skipping."
fi

# --- Install / update the Valheim server (Steam app 896660) ---
echo ">>> Downloading Valheim server (this can take a while)..."
mkdir -p "$VALHEIM_DIR"

if sudo -u "$STEAM_USER" bash <<EOF
"$STEAMCMD_DIR/steamcmd.sh" \
    +login anonymous \
    +force_install_dir "$VALHEIM_DIR" \
    +app_update 896660 validate \
    +quit
EOF
then
    echo ""
    echo "================================================="
    echo " [SUCCESS] Valheim server installed successfully!"
    echo "================================================="
    echo ""
else
    echo ""
    echo "================================================="
    echo " [ERROR] SteamCMD failed to install Valheim."
    echo "================================================="
    echo ""
    exit 1
fi

# ------------------------------------------------------------------
# Deploy scripts, config and systemd unit
# ------------------------------------------------------------------
echo ">>> Deploying scripts and configuration..."
mkdir -p "${VALHEIM_DIR}/logs" "${VALHEIM_DIR}/backups" "$CONFIG_DIR"
install -m 755 -o "$STEAM_USER" -g "$STEAM_USER" \
    "$SCRIPTS_SRC/start_valheim.sh" "${VALHEIM_DIR}/start_valheim.sh"
install -m 755 -o "$STEAM_USER" -g "$STEAM_USER" \
    "$SCRIPTS_SRC/update.sh" "${VALHEIM_DIR}/update.sh"
install -m 755 -o "$STEAM_USER" -g "$STEAM_USER" \
    "$SCRIPTS_SRC/backup.sh" "${VALHEIM_DIR}/backup.sh"

cat > "$ENV_FILE" <<EOF
# Valheim server configuration - generated by install.sh
SERVER_NAME="${SERVER_NAME}"
WORLD_NAME="${WORLD_NAME}"
SERVER_PORT="${SERVER_PORT}"
SERVER_PASSWORD="${SERVER_PASSWORD}"
PUBLIC_LISTING="${PUBLIC_LISTING}"
BACKUP_RETENTION_DAYS="${BACKUP_RETENTION}"
EOF
chown root:"$STEAM_USER" "$ENV_FILE"
chmod 640 "$ENV_FILE"

install -m 644 "$(dirname "$0")/config/valheim.service" \
    /etc/systemd/system/valheim.service
systemctl daemon-reload
systemctl enable valheim.service

# ------------------------------------------------------------------
# Firewall: open the 3 game ports (UDP)
# ------------------------------------------------------------------
echo ">>> Opening UDP ports ${SERVER_PORT}-$((SERVER_PORT + 2)) in nftables..."
nft add rule inet filter input udp dport "${SERVER_PORT}-${ADDITIONAL_PORT:-$((SERVER_PORT + 2))}" accept 2>/dev/null || true

# ------------------------------------------------------------------
# Nightly backup cron job
# ------------------------------------------------------------------
CRON_LINE="0 4 * * * ${VALHEIM_DIR}/backup.sh >> ${VALHEIM_DIR}/logs/backup.log 2>&1"
(crontab -u "$STEAM_USER" -l 2>/dev/null | grep -v "backup.sh"; echo "$CRON_LINE") \
    | crontab -u "$STEAM_USER" -

# ------------------------------------------------------------------
# Done
# ------------------------------------------------------------------
echo ""
echo "==============================================="
echo " Installation complete!"
echo "==============================================="
echo " Start the server:   systemctl start valheim"
echo " Check status:       systemctl status valheim"
echo " Watch the logs:     journalctl -u valheim -f"
echo " Config file:        $ENV_FILE"
echo ""
echo " Remember: ports ${SERVER_PORT}-$((SERVER_PORT + 2))/UDP must also"
echo " be forwarded on your router if the server is behind NAT."
echo ""
read -r -p "Start the server now? [Y/n]: " START_NOW
if [[ ! "$START_NOW" =~ ^[Nn]$ ]]; then
    systemctl start valheim
    sleep 5
    systemctl status valheim --no-pager || true
fi